langchain_tracing_v2 = "true"
langchain_project = "groq-chat"
langchain_endpoint = "https://api.smith.langchain.com"
langchain_api_key = "ls__07a77891363e4508ac042563b30d24cc"
tavily_api_key = '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'
groq_api_key = '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'
